In [1]:
import pandas as pd

In [18]:
# import data
ind = {}
for i in range(22):
    ind["ind_t%s" % str(i+1)] = pd.read_csv("ind_t%s.csv" % str(i+1))

In [34]:
# join data
join_ind = ind['ind_t1']
for i in range(2,23):
    join_ind = join_ind.join(ind['ind_t%s' %str(i)].iloc[:,5:])

In [55]:
join_ind.head()

,indicadores_t1.cod_ccaa,indicadores_t1.cod_prov,indicadores_t1.cod_muni,indicadores_t1.distrito,indicadores_t1.seccion,indicadores_t1.total_poblacion,indicadores_t2.total_hombres,indicadores_t2.total_mujeres,indicadores_t3.total_rango_1,indicadores_t3.total_rango_2,...,indicadores_t20.total_hab_7,indicadores_t20.total_hab_8,indicadores_t20.total_hab_9,indicadores_t21.total_hogares,indicadores_t22.total_hoga_1p,indicadores_t22.total_hoga_2p,indicadores_t22.total_hoga_3p,indicadores_t22.total_hoga_4p,indicadores_t22.total_hoga_5p,indicadores_t22.total_hoga_6p
0,13,28,79,1,1,1205,480.0,725,150.0,700,...,NaN,NaN,75.0,490.0,170.0,160.0,65.0,50.0,0.0,50.0
1,13,28,79,1,2,855,355.0,505,75.0,665,...,NaN,NaN,NaN,485.0,195.0,240.0,NaN,NaN,NaN,NaN
2,13,28,79,1,3,1795,880.0,920,130.0,1350,...,25.0,0.0,65.0,920.0,380.0,320.0,115.0,110.0,0.0,0.0
3,13,28,79,1,4,1070,495.0,575,130.0,785,...,NaN,NaN,NaN,550.0,300.0,70.0,130.0,30.0,0.0,20.0
4,13,28,79,1,6,1950,895.0,1055,200.0,1305,...,10.0,70.0,25.0,960.0,455.0,210.0,180.0,70.0,20.0,30.0

In [81]:
join_ind.shape

(2409, 150)

In [83]:
# check missing values for each column
join_ind.isnull().sum().sort_values(ascending=False)

indicadores_t5.total_nac_lnac_16       2216
indicadores_t5.total_nac_lnac_15       2216
indicadores_t5.total_nac_lnac_11       2216
indicadores_t5.total_nac_lnac_5        2216
indicadores_t5.total_nac_lnac_3        2215
indicadores_t5.total_nac_lnac_12       2213
indicadores_t5.total_nac_lnac_13       2213
indicadores_t5.total_nac_lnac_7        2211
indicadores_t5.total_nac_lnac_6        2203
indicadores_t5.total_nac_lnac_2        2196
indicadores_t5.total_nac_lnac_8        2194
indicadores_t5.total_nac_lnac_14       2181
indicadores_t5.total_nac_lnac_9        2044
indicadores_t5.total_nac_lnac_4        2035
indicadores_t19.total_tam_1            1921
indicadores_t19.total_tam_9            1858
indicadores_t19.total_tam_10           1816
indicadores_t19.total_tam_8            1719
indicadores_t20.total_hab_1            1701
indicadores_t20.total_hab_8            1701
indicadores_t20.total_hab_9            1691
indicadores_t19.total_tam_7            1689
indicadores_t20.total_hab_7            1625
indicadores_t20.total_hab_2            1551
indicadores_t19.total_tam_2            1468
indicadores_t19.total_tam_6            1420
indicadores_t15.total_rang2_analf      1354
indicadores_t15.total_rang2_sin_est    1349
indicadores_t5.total_nac_lnac_10       1336
indicadores_t15.total_rang2_est_g1     1328
                                       ...
indicadores_t9.total_esp_rango3           3
indicadores_t16.total_viviendas           2
indicadores_t17.total_principales         2
indicadores_t14.total_ext_analf           2
indicadores_t21.total_hogares             2
indicadores_t8.total_muj_nac_ext          2
indicadores_t8.total_hom_rnac_ext         2
indicadores_t3.total_rango_3              2
indicadores_t3.total_rango_1              2
indicadores_t4.total_lnac_1               1
indicadores_t2.total_hombres              1
indicadores_t7.total_hom_rango2           1
indicadores_t5.total_nac_lnac_1           1
indicadores_t6.total_nac_esp              1
indicadores_t10.total_solteros            1
indicadores_t9.total_esp_rango2           1
indicadores_t8.total_muj_nac_esp          1
indicadores_t8.total_hom_nac_esp          1
indicadores_t1.total_poblacion            0
indicadores_t1.cod_prov                   0
indicadores_t1.cod_muni                   0
indicadores_t1.distrito                   0
indicadores_t1.seccion                    0
indicadores_t7.total_muj_rango2           0
indicadores_t6.total_nac_ext              0
indicadores_t2.total_mujeres              0
indicadores_t12.total_estudios_g2         0
indicadores_t3.total_rango_2              0
indicadores_t10.total_casados             0
indicadores_t1.cod_ccaa                   0
dtype: int64

In [86]:
# output dataframe to csv
join_ind.to_csv('joined_indicators.csv')

In [60]:
# group by district and sum up the section feature values for each district
df = join_ind.groupby(['indicadores_t1.cod_ccaa', 'indicadores_t1.cod_prov','indicadores_t1.cod_muni','indicadores_t1.distrito']).sum()

In [74]:
# delete the column of section number
df = df.drop('indicadores_t1.seccion', axis=1)

In [76]:
df.head()

                                                                                                 indicadores_t1.total_poblacion  \
indicadores_t1.cod_ccaa indicadores_t1.cod_prov indicadores_t1.cod_muni indicadores_t1.distrito
13                      28                      79                      1                                                135590
                                                                        2                                                152235
                                                                        3                                                119740
                                                                        4                                                143390
                                                                        5                                                143740

                                                                                                 indicadores_t2.total_hombres  \
indicadores_t1.cod_ccaa indicadores_t1.cod_prov indicadores_t1.cod_muni indicadores_t1.distrito
13                      28                      79                      1                                             66990.0
                                                                        2                                             70735.0
                                                                        3                                             54370.0
                                                                        4                                             63105.0
                                                                        5                                             64555.0

                                                                                                 indicadores_t2.total_mujeres  \
indicadores_t1.cod_ccaa indicadores_t1.cod_prov indicadores_t1.cod_muni indicadores_t1.distrito
13                      28                      79                      1                                               68605
                                                                        2                                               81465
                                                                        3                                               65345
                                                                        4                                               80255
                                                                        5                                               79190

                                                                                                 indicadores_t3.total_rango_1  \
indicadores_t1.cod_ccaa indicadores_t1.cod_prov indicadores_t1.cod_muni indicadores_t1.distrito
13                      28                      79                      1                                             13035.0
                                                                        2                                             20055.0
                                                                        3                                             14735.0
                                                                        4                                             16705.0
                                                                        5                                             19535.0

                                                                                                 indicadores_t3.total_rango_2  \
indicadores_t1.cod_ccaa indicadores_t1.cod_prov indicadores_t1.cod_muni indicadores_t1.distrito
13                      28                      79                      1                                              101555
                                                                        2                                              106285
                                                                        3                                               77960
                                                                        4                                               94300
                                                                        5                                               92920

                                                                                                 indicadores_t3.total_rango_3  \
indicadores_t1.cod_ccaa indicadores_t1.cod_prov indicadores_t1.cod_muni indicadores_t1.distrito
13                      28                      79                      1                                             20975.0
                                                                        2                                             25905.0
                                                                        3                                             27060.0
                                                                        4                                             32360.0
                                                                        5                                             31305.0

                                                                                                 indicadores_t4.total_lnac_1  \
indicadores_t1.cod_ccaa indicadores_t1.cod_prov indicadores_t1.cod_muni indicadores_t1.distrito
13                      28                      79                      1                                           100065.0
                                                                        2                                           129985.0
                                                                        3                                           107940.0
                                                                        4                                           122375.0
                                                                        5                                           125415.0

                                                                                                 indicadores_t4.total_lnac_2  \
indicadores_t1.cod_ccaa indicadores_t1.cod_prov indicadores_t1.cod_muni indicadores_t1.distrito
13                      28                      79                      1                                             5820.0
                                                                        2                                             4235.0
                                                                        3                                             1990.0
                                                                        4                                             3180.0
                                                                        5                                             4165.0

                                                                                                 indicadores_t4.total_lnac_3  \
indicadores_t1.cod_ccaa indicadores_t1.cod_prov indicadores_t1.cod_muni indicadores_t1.distrito
13                      28                      79                      1                                              435.0
                                                                        2                                              665.0
                                                                        3                                              350.0
                                                                        4                                              410.0
                                                                        5                                              430.0

                                                                                                 indicadores_t4.total_lnac_4  \
indicadores_t1.cod_ccaa indicadores_t1.cod_prov indicadores_t1.cod_muni indicadores_t1.distrito
13                      28                      79                      1                                             1940.0
                                                                        2                                             1170.0
                                                                        3                                              725.0
                                                                        4                                              645.0
                                                                        5                                              990.0

                                                                                                             ...                \
indicadores_t1.cod_ccaa indicadores_t1.cod_prov indicadores_t1.cod_muni indicadores_t1.distrito              ...
13                      28                      79                      1                                    ...
                                                                        2                                    ...
                                                                        3                                    ...
                                                                        4                                    ...
                                                                        5                                    ...

                                                                                                 indicadores_t20.total_hab_7  \
indicadores_t1.cod_ccaa indicadores_t1.cod_prov indicadores_t1.cod_muni indicadores_t1.distrito
13                      28                      79                      1                                              560.0
                                                                        2                                              720.0
                                                                        3                                             1540.0
                                                                        4                                             2740.0
                                                                        5                                             2640.0

                                                                                                 indicadores_t20.total_hab_8  \
indicadores_t1.cod_ccaa indicadores_t1.cod_prov indicadores_t1.cod_muni indicadores_t1.distrito
13                      28                      79                      1                                              315.0
                                                                        2                                              175.0
                                                                        3                                              270.0
                                                                        4                                              565.0
                                                                        5                                             1015.0

                                                                                                 indicadores_t20.total_hab_9  \
indicadores_t1.cod_ccaa indicadores_t1.cod_prov indicadores_t1.cod_muni indicadores_t1.distrito
13                      28                      79                      1                                              320.0
                                                                        2                                              115.0
                                                                        3                                              140.0
                                                                        4                                              895.0
                                                                        5                                             1420.0

                                                                                                 indicadores_t21.total_hogares  \
indicadores_t1.cod_ccaa indicadores_t1.cod_prov indicadores_t1.cod_muni indicadores_t1.distrito
13                      28                      79                      1                                              70505.0
                                                                        2                                              67160.0
                                                                        3                                              51025.0
                                                                        4                                              62715.0
                                                                        5                                              60770.0

                                                                                                 indicadores_t22.total_hoga_1p  \
indicadores_t1.cod_ccaa indicadores_t1.cod_prov indicadores_t1.cod_muni indicadores_t1.distrito
13                      28                      79                      1                                              31565.0
                                                                        2                                              21990.0
                                                                        3                                              14810.0
                                                                        4                                              21035.0
                                                                        5                                              19285.0

                                                                                                 indicadores_t22.total_hoga_2p  \
indicadores_t1.cod_ccaa indicadores_t1.cod_prov indicadores_t1.cod_muni indicadores_t1.distrito
13                      28                      79                      1                                              22825.0
                                                                        2                                              21195.0
                                                                        3                                              16790.0
                                                                        4                                              19280.0
                                                                        5                                              18795.0

                                                                                                 indicadores_t22.total_hoga_3p  \
indicadores_t1.cod_ccaa indicadores_t1.cod_prov indicadores_t1.cod_muni indicadores_t1.distrito
13                      28                      79                      1                                               8260.0
                                                                        2                                              11260.0
                                                                        3                                               8845.0
                                                                        4                                               9220.0
                                                                        5                                               9825.0

                                                                                                 indicadores_t22.total_hoga_4p  \
indicadores_t1.cod_ccaa indicadores_t1.cod_prov indicadores_t1.cod_muni indicadores_t1.distrito
13                      28                      79                      1                                               4010.0
                                                                        2                                               9250.0
                                                                        3                                               6810.0
                                                                        4                                               6580.0
                                                                        5                                               7470.0

                                                                                                 indicadores_t22.total_hoga_5p  \
indicadores_t1.cod_ccaa indicadores_t1.cod_prov indicadores_t1.cod_muni indicadores_t1.distrito
13                      28                      79                      1                                               1445.0
                                                                        2                                               1875.0
                                                                        3                                               1820.0
                                                                        4                                               2000.0
                                                                        5                                               2820.0

                                                                                                 indicadores_t22.total_hoga_6p
indicadores_t1.cod_ccaa indicadores_t1.cod_prov indicadores_t1.cod_muni indicadores_t1.distrito
13                      28                      79                      1                                                520.0
                                                                        2                                                665.0
                                                                        3                                                430.0
                                                                        4                                                935.0
                                                                        5                                               1325.0

[5 rows x 145 columns]

In [87]:
# output dataframe to csv
df.to_csv('joined_indicators_groupby_district.csv')